name: Deploy to Mac

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOYMENT_MAC_IP }}
          username: ${{ secrets.DEPLOYMENT_MAC_USER }}
          key: ${{ secrets.PRAVEEN_MAC_SSH_KEY }}
          script: |
            cd path/to/your/repo  # Update this!
            git pull origin main
            docker-compose down
            docker-compose up -d --build